apiVersion: apps/v1
kind: deployment
metadata:
  name: dotnet-app-deployment
  labels:
    app: dotnet-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      containers:
       - name: dotnet-app
         image: prasanth202/dotnet-image:latest
         ports:
         - containerPort: 80


